// Generated by gencpp from file rearrange/GetSceneObjectList.msg
// DO NOT EDIT!


#ifndef REARRANGE_MESSAGE_GETSCENEOBJECTLIST_H
#define REARRANGE_MESSAGE_GETSCENEOBJECTLIST_H

#include <ros/service_traits.h>


#include <rearrange/GetSceneObjectListRequest.h>
#include <rearrange/GetSceneObjectListResponse.h>


namespace rearrange
{

struct GetSceneObjectList
{

typedef GetSceneObjectListRequest Request;
typedef GetSceneObjectListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSceneObjectList
} // namespace rearrange


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rearrange::GetSceneObjectList > {
  static const char* value()
  {
    return "49b647e60541a19da96e1aeac31fdfb8";
  }

  static const char* value(const ::rearrange::GetSceneObjectList&) { return value(); }
};

template<>
struct DataType< ::rearrange::GetSceneObjectList > {
  static const char* value()
  {
    return "rearrange/GetSceneObjectList";
  }

  static const char* value(const ::rearrange::GetSceneObjectList&) { return value(); }
};


// service_traits::MD5Sum< ::rearrange::GetSceneObjectListRequest> should match
// service_traits::MD5Sum< ::rearrange::GetSceneObjectList >
template<>
struct MD5Sum< ::rearrange::GetSceneObjectListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rearrange::GetSceneObjectList >::value();
  }
  static const char* value(const ::rearrange::GetSceneObjectListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rearrange::GetSceneObjectListRequest> should match
// service_traits::DataType< ::rearrange::GetSceneObjectList >
template<>
struct DataType< ::rearrange::GetSceneObjectListRequest>
{
  static const char* value()
  {
    return DataType< ::rearrange::GetSceneObjectList >::value();
  }
  static const char* value(const ::rearrange::GetSceneObjectListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rearrange::GetSceneObjectListResponse> should match
// service_traits::MD5Sum< ::rearrange::GetSceneObjectList >
template<>
struct MD5Sum< ::rearrange::GetSceneObjectListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rearrange::GetSceneObjectList >::value();
  }
  static const char* value(const ::rearrange::GetSceneObjectListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rearrange::GetSceneObjectListResponse> should match
// service_traits::DataType< ::rearrange::GetSceneObjectList >
template<>
struct DataType< ::rearrange::GetSceneObjectListResponse>
{
  static const char* value()
  {
    return DataType< ::rearrange::GetSceneObjectList >::value();
  }
  static const char* value(const ::rearrange::GetSceneObjectListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REARRANGE_MESSAGE_GETSCENEOBJECTLIST_H
