// Generated by gencpp from file rearrange/NavigateDrinkFeedback.msg
// DO NOT EDIT!


#ifndef REARRANGE_MESSAGE_NAVIGATEDRINKFEEDBACK_H
#define REARRANGE_MESSAGE_NAVIGATEDRINKFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rearrange
{
template <class ContainerAllocator>
struct NavigateDrinkFeedback_
{
  typedef NavigateDrinkFeedback_<ContainerAllocator> Type;

  NavigateDrinkFeedback_()
    : success(false)  {
    }
  NavigateDrinkFeedback_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateDrinkFeedback_

typedef ::rearrange::NavigateDrinkFeedback_<std::allocator<void> > NavigateDrinkFeedback;

typedef boost::shared_ptr< ::rearrange::NavigateDrinkFeedback > NavigateDrinkFeedbackPtr;
typedef boost::shared_ptr< ::rearrange::NavigateDrinkFeedback const> NavigateDrinkFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rearrange

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rearrange/NavigateDrinkFeedback";
  }

  static const char* value(const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateDrinkFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rearrange::NavigateDrinkFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rearrange::NavigateDrinkFeedback_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REARRANGE_MESSAGE_NAVIGATEDRINKFEEDBACK_H
