// Generated by gencpp from file rearrange/NavigateDrinkResult.msg
// DO NOT EDIT!


#ifndef REARRANGE_MESSAGE_NAVIGATEDRINKRESULT_H
#define REARRANGE_MESSAGE_NAVIGATEDRINKRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rearrange
{
template <class ContainerAllocator>
struct NavigateDrinkResult_
{
  typedef NavigateDrinkResult_<ContainerAllocator> Type;

  NavigateDrinkResult_()
    : current_x(0.0)
    , current_y(0.0)
    , current_orientation_z(0.0)
    , current_orientation_w(0.0)  {
    }
  NavigateDrinkResult_(const ContainerAllocator& _alloc)
    : current_x(0.0)
    , current_y(0.0)
    , current_orientation_z(0.0)
    , current_orientation_w(0.0)  {
  (void)_alloc;
    }



   typedef float _current_x_type;
  _current_x_type current_x;

   typedef float _current_y_type;
  _current_y_type current_y;

   typedef float _current_orientation_z_type;
  _current_orientation_z_type current_orientation_z;

   typedef float _current_orientation_w_type;
  _current_orientation_w_type current_orientation_w;





  typedef boost::shared_ptr< ::rearrange::NavigateDrinkResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rearrange::NavigateDrinkResult_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateDrinkResult_

typedef ::rearrange::NavigateDrinkResult_<std::allocator<void> > NavigateDrinkResult;

typedef boost::shared_ptr< ::rearrange::NavigateDrinkResult > NavigateDrinkResultPtr;
typedef boost::shared_ptr< ::rearrange::NavigateDrinkResult const> NavigateDrinkResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rearrange::NavigateDrinkResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rearrange::NavigateDrinkResult_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkResult_<ContainerAllocator2> & rhs)
{
  return lhs.current_x == rhs.current_x &&
    lhs.current_y == rhs.current_y &&
    lhs.current_orientation_z == rhs.current_orientation_z &&
    lhs.current_orientation_w == rhs.current_orientation_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rearrange::NavigateDrinkResult_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rearrange

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5332c945bfb39768317dc31e78fb16d0";
  }

  static const char* value(const ::rearrange::NavigateDrinkResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5332c945bfb39768ULL;
  static const uint64_t static_value2 = 0x317dc31e78fb16d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rearrange/NavigateDrinkResult";
  }

  static const char* value(const ::rearrange::NavigateDrinkResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"float32 current_x\n"
"float32 current_y\n"
"float32 current_orientation_z\n"
"float32 current_orientation_w\n"
;
  }

  static const char* value(const ::rearrange::NavigateDrinkResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_x);
      stream.next(m.current_y);
      stream.next(m.current_orientation_z);
      stream.next(m.current_orientation_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateDrinkResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rearrange::NavigateDrinkResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rearrange::NavigateDrinkResult_<ContainerAllocator>& v)
  {
    s << indent << "current_x: ";
    Printer<float>::stream(s, indent + "  ", v.current_x);
    s << indent << "current_y: ";
    Printer<float>::stream(s, indent + "  ", v.current_y);
    s << indent << "current_orientation_z: ";
    Printer<float>::stream(s, indent + "  ", v.current_orientation_z);
    s << indent << "current_orientation_w: ";
    Printer<float>::stream(s, indent + "  ", v.current_orientation_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REARRANGE_MESSAGE_NAVIGATEDRINKRESULT_H
