// Generated by gencpp from file rearrange/NavigateDrinkActionGoal.msg
// DO NOT EDIT!


#ifndef REARRANGE_MESSAGE_NAVIGATEDRINKACTIONGOAL_H
#define REARRANGE_MESSAGE_NAVIGATEDRINKACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <rearrange/NavigateDrinkGoal.h>

namespace rearrange
{
template <class ContainerAllocator>
struct NavigateDrinkActionGoal_
{
  typedef NavigateDrinkActionGoal_<ContainerAllocator> Type;

  NavigateDrinkActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  NavigateDrinkActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::rearrange::NavigateDrinkGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateDrinkActionGoal_

typedef ::rearrange::NavigateDrinkActionGoal_<std::allocator<void> > NavigateDrinkActionGoal;

typedef boost::shared_ptr< ::rearrange::NavigateDrinkActionGoal > NavigateDrinkActionGoalPtr;
typedef boost::shared_ptr< ::rearrange::NavigateDrinkActionGoal const> NavigateDrinkActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rearrange

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ebbb6521df8201312e3ab1f230a8a31";
  }

  static const char* value(const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ebbb6521df82013ULL;
  static const uint64_t static_value2 = 0x12e3ab1f230a8a31ULL;
};

template<class ContainerAllocator>
struct DataType< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rearrange/NavigateDrinkActionGoal";
  }

  static const char* value(const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"NavigateDrinkGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rearrange/NavigateDrinkGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string drink_name\n"
"float32 target_x\n"
"float32 target_y\n"
"float32 target_orientation_z\n"
"float32 target_orientation_w\n"
;
  }

  static const char* value(const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateDrinkActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REARRANGE_MESSAGE_NAVIGATEDRINKACTIONGOAL_H
