// Generated by gencpp from file rearrange/NavigateDrinkGoal.msg
// DO NOT EDIT!


#ifndef REARRANGE_MESSAGE_NAVIGATEDRINKGOAL_H
#define REARRANGE_MESSAGE_NAVIGATEDRINKGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rearrange
{
template <class ContainerAllocator>
struct NavigateDrinkGoal_
{
  typedef NavigateDrinkGoal_<ContainerAllocator> Type;

  NavigateDrinkGoal_()
    : drink_name()
    , target_x(0.0)
    , target_y(0.0)
    , target_orientation_z(0.0)
    , target_orientation_w(0.0)  {
    }
  NavigateDrinkGoal_(const ContainerAllocator& _alloc)
    : drink_name(_alloc)
    , target_x(0.0)
    , target_y(0.0)
    , target_orientation_z(0.0)
    , target_orientation_w(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _drink_name_type;
  _drink_name_type drink_name;

   typedef float _target_x_type;
  _target_x_type target_x;

   typedef float _target_y_type;
  _target_y_type target_y;

   typedef float _target_orientation_z_type;
  _target_orientation_z_type target_orientation_z;

   typedef float _target_orientation_w_type;
  _target_orientation_w_type target_orientation_w;





  typedef boost::shared_ptr< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateDrinkGoal_

typedef ::rearrange::NavigateDrinkGoal_<std::allocator<void> > NavigateDrinkGoal;

typedef boost::shared_ptr< ::rearrange::NavigateDrinkGoal > NavigateDrinkGoalPtr;
typedef boost::shared_ptr< ::rearrange::NavigateDrinkGoal const> NavigateDrinkGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rearrange::NavigateDrinkGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rearrange::NavigateDrinkGoal_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkGoal_<ContainerAllocator2> & rhs)
{
  return lhs.drink_name == rhs.drink_name &&
    lhs.target_x == rhs.target_x &&
    lhs.target_y == rhs.target_y &&
    lhs.target_orientation_z == rhs.target_orientation_z &&
    lhs.target_orientation_w == rhs.target_orientation_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rearrange::NavigateDrinkGoal_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rearrange

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60af8d6775a7d74b1f37c4f2a62945fb";
  }

  static const char* value(const ::rearrange::NavigateDrinkGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60af8d6775a7d74bULL;
  static const uint64_t static_value2 = 0x1f37c4f2a62945fbULL;
};

template<class ContainerAllocator>
struct DataType< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rearrange/NavigateDrinkGoal";
  }

  static const char* value(const ::rearrange::NavigateDrinkGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string drink_name\n"
"float32 target_x\n"
"float32 target_y\n"
"float32 target_orientation_z\n"
"float32 target_orientation_w\n"
;
  }

  static const char* value(const ::rearrange::NavigateDrinkGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drink_name);
      stream.next(m.target_x);
      stream.next(m.target_y);
      stream.next(m.target_orientation_z);
      stream.next(m.target_orientation_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateDrinkGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rearrange::NavigateDrinkGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rearrange::NavigateDrinkGoal_<ContainerAllocator>& v)
  {
    s << indent << "drink_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.drink_name);
    s << indent << "target_x: ";
    Printer<float>::stream(s, indent + "  ", v.target_x);
    s << indent << "target_y: ";
    Printer<float>::stream(s, indent + "  ", v.target_y);
    s << indent << "target_orientation_z: ";
    Printer<float>::stream(s, indent + "  ", v.target_orientation_z);
    s << indent << "target_orientation_w: ";
    Printer<float>::stream(s, indent + "  ", v.target_orientation_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REARRANGE_MESSAGE_NAVIGATEDRINKGOAL_H
