// Generated by gencpp from file rearrange/NavigateDrinkAction.msg
// DO NOT EDIT!


#ifndef REARRANGE_MESSAGE_NAVIGATEDRINKACTION_H
#define REARRANGE_MESSAGE_NAVIGATEDRINKACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rearrange/NavigateDrinkActionGoal.h>
#include <rearrange/NavigateDrinkActionResult.h>
#include <rearrange/NavigateDrinkActionFeedback.h>

namespace rearrange
{
template <class ContainerAllocator>
struct NavigateDrinkAction_
{
  typedef NavigateDrinkAction_<ContainerAllocator> Type;

  NavigateDrinkAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  NavigateDrinkAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::rearrange::NavigateDrinkActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::rearrange::NavigateDrinkActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::rearrange::NavigateDrinkAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rearrange::NavigateDrinkAction_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateDrinkAction_

typedef ::rearrange::NavigateDrinkAction_<std::allocator<void> > NavigateDrinkAction;

typedef boost::shared_ptr< ::rearrange::NavigateDrinkAction > NavigateDrinkActionPtr;
typedef boost::shared_ptr< ::rearrange::NavigateDrinkAction const> NavigateDrinkActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rearrange::NavigateDrinkAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rearrange::NavigateDrinkAction_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rearrange::NavigateDrinkAction_<ContainerAllocator1> & lhs, const ::rearrange::NavigateDrinkAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rearrange

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rearrange::NavigateDrinkAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rearrange::NavigateDrinkAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rearrange::NavigateDrinkAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad8ae92042c341ed02b3cb999b960fa4";
  }

  static const char* value(const ::rearrange::NavigateDrinkAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad8ae92042c341edULL;
  static const uint64_t static_value2 = 0x02b3cb999b960fa4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rearrange/NavigateDrinkAction";
  }

  static const char* value(const ::rearrange::NavigateDrinkAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"NavigateDrinkActionGoal action_goal\n"
"NavigateDrinkActionResult action_result\n"
"NavigateDrinkActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: rearrange/NavigateDrinkActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"NavigateDrinkGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rearrange/NavigateDrinkGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string drink_name\n"
"float32 target_x\n"
"float32 target_y\n"
"float32 target_orientation_z\n"
"float32 target_orientation_w\n"
"\n"
"================================================================================\n"
"MSG: rearrange/NavigateDrinkActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"NavigateDrinkResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rearrange/NavigateDrinkResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"float32 current_x\n"
"float32 current_y\n"
"float32 current_orientation_z\n"
"float32 current_orientation_w\n"
"\n"
"================================================================================\n"
"MSG: rearrange/NavigateDrinkActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"NavigateDrinkFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: rearrange/NavigateDrinkFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::rearrange::NavigateDrinkAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateDrinkAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rearrange::NavigateDrinkAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rearrange::NavigateDrinkAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::rearrange::NavigateDrinkActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::rearrange::NavigateDrinkActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::rearrange::NavigateDrinkActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REARRANGE_MESSAGE_NAVIGATEDRINKACTION_H
