// Generated by gencpp from file rearrange/SetInitTiagoPose.msg
// DO NOT EDIT!


#ifndef REARRANGE_MESSAGE_SETINITTIAGOPOSE_H
#define REARRANGE_MESSAGE_SETINITTIAGOPOSE_H

#include <ros/service_traits.h>


#include <rearrange/SetInitTiagoPoseRequest.h>
#include <rearrange/SetInitTiagoPoseResponse.h>


namespace rearrange
{

struct SetInitTiagoPose
{

typedef SetInitTiagoPoseRequest Request;
typedef SetInitTiagoPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitTiagoPose
} // namespace rearrange


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rearrange::SetInitTiagoPose > {
  static const char* value()
  {
    return "506d0acd0d4a87fa64b5270d2249c2f0";
  }

  static const char* value(const ::rearrange::SetInitTiagoPose&) { return value(); }
};

template<>
struct DataType< ::rearrange::SetInitTiagoPose > {
  static const char* value()
  {
    return "rearrange/SetInitTiagoPose";
  }

  static const char* value(const ::rearrange::SetInitTiagoPose&) { return value(); }
};


// service_traits::MD5Sum< ::rearrange::SetInitTiagoPoseRequest> should match
// service_traits::MD5Sum< ::rearrange::SetInitTiagoPose >
template<>
struct MD5Sum< ::rearrange::SetInitTiagoPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rearrange::SetInitTiagoPose >::value();
  }
  static const char* value(const ::rearrange::SetInitTiagoPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rearrange::SetInitTiagoPoseRequest> should match
// service_traits::DataType< ::rearrange::SetInitTiagoPose >
template<>
struct DataType< ::rearrange::SetInitTiagoPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rearrange::SetInitTiagoPose >::value();
  }
  static const char* value(const ::rearrange::SetInitTiagoPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rearrange::SetInitTiagoPoseResponse> should match
// service_traits::MD5Sum< ::rearrange::SetInitTiagoPose >
template<>
struct MD5Sum< ::rearrange::SetInitTiagoPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rearrange::SetInitTiagoPose >::value();
  }
  static const char* value(const ::rearrange::SetInitTiagoPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rearrange::SetInitTiagoPoseResponse> should match
// service_traits::DataType< ::rearrange::SetInitTiagoPose >
template<>
struct DataType< ::rearrange::SetInitTiagoPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rearrange::SetInitTiagoPose >::value();
  }
  static const char* value(const ::rearrange::SetInitTiagoPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REARRANGE_MESSAGE_SETINITTIAGOPOSE_H
