// Generated by gencpp from file rearrange/UpdateObjectList.msg
// DO NOT EDIT!


#ifndef REARRANGE_MESSAGE_UPDATEOBJECTLIST_H
#define REARRANGE_MESSAGE_UPDATEOBJECTLIST_H

#include <ros/service_traits.h>


#include <rearrange/UpdateObjectListRequest.h>
#include <rearrange/UpdateObjectListResponse.h>


namespace rearrange
{

struct UpdateObjectList
{

typedef UpdateObjectListRequest Request;
typedef UpdateObjectListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateObjectList
} // namespace rearrange


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rearrange::UpdateObjectList > {
  static const char* value()
  {
    return "07fb332925eec5f4d2f3c7b2da4de91d";
  }

  static const char* value(const ::rearrange::UpdateObjectList&) { return value(); }
};

template<>
struct DataType< ::rearrange::UpdateObjectList > {
  static const char* value()
  {
    return "rearrange/UpdateObjectList";
  }

  static const char* value(const ::rearrange::UpdateObjectList&) { return value(); }
};


// service_traits::MD5Sum< ::rearrange::UpdateObjectListRequest> should match
// service_traits::MD5Sum< ::rearrange::UpdateObjectList >
template<>
struct MD5Sum< ::rearrange::UpdateObjectListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rearrange::UpdateObjectList >::value();
  }
  static const char* value(const ::rearrange::UpdateObjectListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rearrange::UpdateObjectListRequest> should match
// service_traits::DataType< ::rearrange::UpdateObjectList >
template<>
struct DataType< ::rearrange::UpdateObjectListRequest>
{
  static const char* value()
  {
    return DataType< ::rearrange::UpdateObjectList >::value();
  }
  static const char* value(const ::rearrange::UpdateObjectListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rearrange::UpdateObjectListResponse> should match
// service_traits::MD5Sum< ::rearrange::UpdateObjectList >
template<>
struct MD5Sum< ::rearrange::UpdateObjectListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rearrange::UpdateObjectList >::value();
  }
  static const char* value(const ::rearrange::UpdateObjectListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rearrange::UpdateObjectListResponse> should match
// service_traits::DataType< ::rearrange::UpdateObjectList >
template<>
struct DataType< ::rearrange::UpdateObjectListResponse>
{
  static const char* value()
  {
    return DataType< ::rearrange::UpdateObjectList >::value();
  }
  static const char* value(const ::rearrange::UpdateObjectListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REARRANGE_MESSAGE_UPDATEOBJECTLIST_H
