// Generated by gencpp from file world_percept_assig3/GetSceneObjectListRequest.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_GETSCENEOBJECTLISTREQUEST_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_GETSCENEOBJECTLISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace world_percept_assig3
{
template <class ContainerAllocator>
struct GetSceneObjectListRequest_
{
  typedef GetSceneObjectListRequest_<ContainerAllocator> Type;

  GetSceneObjectListRequest_()
    : object_name()  {
    }
  GetSceneObjectListRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_name_type;
  _object_name_type object_name;





  typedef boost::shared_ptr< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSceneObjectListRequest_

typedef ::world_percept_assig3::GetSceneObjectListRequest_<std::allocator<void> > GetSceneObjectListRequest;

typedef boost::shared_ptr< ::world_percept_assig3::GetSceneObjectListRequest > GetSceneObjectListRequestPtr;
typedef boost::shared_ptr< ::world_percept_assig3::GetSceneObjectListRequest const> GetSceneObjectListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator1> & lhs, const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_name == rhs.object_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator1> & lhs, const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace world_percept_assig3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f12226348d323c2e5b2031b3da53f1b";
  }

  static const char* value(const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f12226348d323c2ULL;
  static const uint64_t static_value2 = 0xe5b2031b3da53f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_percept_assig3/GetSceneObjectListRequest";
  }

  static const char* value(const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Name of the target object. You can use \"all\" to get all the objects in the scene.\n"
"string object_name\n"
"\n"
;
  }

  static const char* value(const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSceneObjectListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_percept_assig3::GetSceneObjectListRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_GETSCENEOBJECTLISTREQUEST_H
