// Generated by gencpp from file world_percept_assig3/GetSceneObjectList.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_GETSCENEOBJECTLIST_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_GETSCENEOBJECTLIST_H

#include <ros/service_traits.h>


#include <world_percept_assig3/GetSceneObjectListRequest.h>
#include <world_percept_assig3/GetSceneObjectListResponse.h>


namespace world_percept_assig3
{

struct GetSceneObjectList
{

typedef GetSceneObjectListRequest Request;
typedef GetSceneObjectListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSceneObjectList
} // namespace world_percept_assig3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_percept_assig3::GetSceneObjectList > {
  static const char* value()
  {
    return "49b647e60541a19da96e1aeac31fdfb8";
  }

  static const char* value(const ::world_percept_assig3::GetSceneObjectList&) { return value(); }
};

template<>
struct DataType< ::world_percept_assig3::GetSceneObjectList > {
  static const char* value()
  {
    return "world_percept_assig3/GetSceneObjectList";
  }

  static const char* value(const ::world_percept_assig3::GetSceneObjectList&) { return value(); }
};


// service_traits::MD5Sum< ::world_percept_assig3::GetSceneObjectListRequest> should match
// service_traits::MD5Sum< ::world_percept_assig3::GetSceneObjectList >
template<>
struct MD5Sum< ::world_percept_assig3::GetSceneObjectListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::GetSceneObjectList >::value();
  }
  static const char* value(const ::world_percept_assig3::GetSceneObjectListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::GetSceneObjectListRequest> should match
// service_traits::DataType< ::world_percept_assig3::GetSceneObjectList >
template<>
struct DataType< ::world_percept_assig3::GetSceneObjectListRequest>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::GetSceneObjectList >::value();
  }
  static const char* value(const ::world_percept_assig3::GetSceneObjectListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_percept_assig3::GetSceneObjectListResponse> should match
// service_traits::MD5Sum< ::world_percept_assig3::GetSceneObjectList >
template<>
struct MD5Sum< ::world_percept_assig3::GetSceneObjectListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::GetSceneObjectList >::value();
  }
  static const char* value(const ::world_percept_assig3::GetSceneObjectListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::GetSceneObjectListResponse> should match
// service_traits::DataType< ::world_percept_assig3::GetSceneObjectList >
template<>
struct DataType< ::world_percept_assig3::GetSceneObjectListResponse>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::GetSceneObjectList >::value();
  }
  static const char* value(const ::world_percept_assig3::GetSceneObjectListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_GETSCENEOBJECTLIST_H
