// Generated by gencpp from file world_percept_assig3/GoToObject.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECT_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECT_H

#include <ros/service_traits.h>


#include <world_percept_assig3/GoToObjectRequest.h>
#include <world_percept_assig3/GoToObjectResponse.h>


namespace world_percept_assig3
{

struct GoToObject
{

typedef GoToObjectRequest Request;
typedef GoToObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToObject
} // namespace world_percept_assig3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_percept_assig3::GoToObject > {
  static const char* value()
  {
    return "b7de194fd0522df85d7a9bdf6a8e6897";
  }

  static const char* value(const ::world_percept_assig3::GoToObject&) { return value(); }
};

template<>
struct DataType< ::world_percept_assig3::GoToObject > {
  static const char* value()
  {
    return "world_percept_assig3/GoToObject";
  }

  static const char* value(const ::world_percept_assig3::GoToObject&) { return value(); }
};


// service_traits::MD5Sum< ::world_percept_assig3::GoToObjectRequest> should match
// service_traits::MD5Sum< ::world_percept_assig3::GoToObject >
template<>
struct MD5Sum< ::world_percept_assig3::GoToObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::GoToObject >::value();
  }
  static const char* value(const ::world_percept_assig3::GoToObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::GoToObjectRequest> should match
// service_traits::DataType< ::world_percept_assig3::GoToObject >
template<>
struct DataType< ::world_percept_assig3::GoToObjectRequest>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::GoToObject >::value();
  }
  static const char* value(const ::world_percept_assig3::GoToObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_percept_assig3::GoToObjectResponse> should match
// service_traits::MD5Sum< ::world_percept_assig3::GoToObject >
template<>
struct MD5Sum< ::world_percept_assig3::GoToObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::GoToObject >::value();
  }
  static const char* value(const ::world_percept_assig3::GoToObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::GoToObjectResponse> should match
// service_traits::DataType< ::world_percept_assig3::GoToObject >
template<>
struct DataType< ::world_percept_assig3::GoToObjectResponse>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::GoToObject >::value();
  }
  static const char* value(const ::world_percept_assig3::GoToObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECT_H
