// Generated by gencpp from file world_percept_assig3/GoToObjectRequest.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECTREQUEST_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace world_percept_assig3
{
template <class ContainerAllocator>
struct GoToObjectRequest_
{
  typedef GoToObjectRequest_<ContainerAllocator> Type;

  GoToObjectRequest_()
    : target_name()  {
    }
  GoToObjectRequest_(const ContainerAllocator& _alloc)
    : target_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_name_type;
  _target_name_type target_name;





  typedef boost::shared_ptr< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToObjectRequest_

typedef ::world_percept_assig3::GoToObjectRequest_<std::allocator<void> > GoToObjectRequest;

typedef boost::shared_ptr< ::world_percept_assig3::GoToObjectRequest > GoToObjectRequestPtr;
typedef boost::shared_ptr< ::world_percept_assig3::GoToObjectRequest const> GoToObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator1> & lhs, const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_name == rhs.target_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator1> & lhs, const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace world_percept_assig3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2008933b3c7227647cbe00c74682331a";
  }

  static const char* value(const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2008933b3c722764ULL;
  static const uint64_t static_value2 = 0x7cbe00c74682331aULL;
};

template<class ContainerAllocator>
struct DataType< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_percept_assig3/GoToObjectRequest";
  }

  static const char* value(const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request part of the service\n"
"# Name of the object to go to\n"
"string target_name\n"
"\n"
;
  }

  static const char* value(const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_percept_assig3::GoToObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECTREQUEST_H
