// Generated by gencpp from file world_percept_assig3/GoToObjectResponse.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECTRESPONSE_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace world_percept_assig3
{
template <class ContainerAllocator>
struct GoToObjectResponse_
{
  typedef GoToObjectResponse_<ContainerAllocator> Type;

  GoToObjectResponse_()
    : linear_velocity(0.0)
    , angular_velocity(0.0)
    , success(false)  {
    }
  GoToObjectResponse_(const ContainerAllocator& _alloc)
    : linear_velocity(0.0)
    , angular_velocity(0.0)
    , success(false)  {
  (void)_alloc;
    }



   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToObjectResponse_

typedef ::world_percept_assig3::GoToObjectResponse_<std::allocator<void> > GoToObjectResponse;

typedef boost::shared_ptr< ::world_percept_assig3::GoToObjectResponse > GoToObjectResponsePtr;
typedef boost::shared_ptr< ::world_percept_assig3::GoToObjectResponse const> GoToObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator1> & lhs, const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.linear_velocity == rhs.linear_velocity &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator1> & lhs, const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace world_percept_assig3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c558baf470dbaeae67290fddedb21092";
  }

  static const char* value(const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc558baf470dbaeaeULL;
  static const uint64_t static_value2 = 0x67290fddedb21092ULL;
};

template<class ContainerAllocator>
struct DataType< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_percept_assig3/GoToObjectResponse";
  }

  static const char* value(const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response part of the service\n"
"# Calculated linear velocity to move towards the object\n"
"float64 linear_velocity\n"
"\n"
"float64 angular_velocity\n"
"\n"
"\n"
"bool success\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_velocity);
      stream.next(m.angular_velocity);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_percept_assig3::GoToObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_GOTOOBJECTRESPONSE_H
