// Generated by gencpp from file world_percept_assig3/LoadKnowledge.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_LOADKNOWLEDGE_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_LOADKNOWLEDGE_H

#include <ros/service_traits.h>


#include <world_percept_assig3/LoadKnowledgeRequest.h>
#include <world_percept_assig3/LoadKnowledgeResponse.h>


namespace world_percept_assig3
{

struct LoadKnowledge
{

typedef LoadKnowledgeRequest Request;
typedef LoadKnowledgeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadKnowledge
} // namespace world_percept_assig3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_percept_assig3::LoadKnowledge > {
  static const char* value()
  {
    return "9d9359c2e08422f16683a8ebec668cb6";
  }

  static const char* value(const ::world_percept_assig3::LoadKnowledge&) { return value(); }
};

template<>
struct DataType< ::world_percept_assig3::LoadKnowledge > {
  static const char* value()
  {
    return "world_percept_assig3/LoadKnowledge";
  }

  static const char* value(const ::world_percept_assig3::LoadKnowledge&) { return value(); }
};


// service_traits::MD5Sum< ::world_percept_assig3::LoadKnowledgeRequest> should match
// service_traits::MD5Sum< ::world_percept_assig3::LoadKnowledge >
template<>
struct MD5Sum< ::world_percept_assig3::LoadKnowledgeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::LoadKnowledge >::value();
  }
  static const char* value(const ::world_percept_assig3::LoadKnowledgeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::LoadKnowledgeRequest> should match
// service_traits::DataType< ::world_percept_assig3::LoadKnowledge >
template<>
struct DataType< ::world_percept_assig3::LoadKnowledgeRequest>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::LoadKnowledge >::value();
  }
  static const char* value(const ::world_percept_assig3::LoadKnowledgeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_percept_assig3::LoadKnowledgeResponse> should match
// service_traits::MD5Sum< ::world_percept_assig3::LoadKnowledge >
template<>
struct MD5Sum< ::world_percept_assig3::LoadKnowledgeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::LoadKnowledge >::value();
  }
  static const char* value(const ::world_percept_assig3::LoadKnowledgeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::LoadKnowledgeResponse> should match
// service_traits::DataType< ::world_percept_assig3::LoadKnowledge >
template<>
struct DataType< ::world_percept_assig3::LoadKnowledgeResponse>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::LoadKnowledge >::value();
  }
  static const char* value(const ::world_percept_assig3::LoadKnowledgeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_LOADKNOWLEDGE_H
