// Generated by gencpp from file world_percept_assig3/LoadKnowledgeRequest.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_LOADKNOWLEDGEREQUEST_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_LOADKNOWLEDGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace world_percept_assig3
{
template <class ContainerAllocator>
struct LoadKnowledgeRequest_
{
  typedef LoadKnowledgeRequest_<ContainerAllocator> Type;

  LoadKnowledgeRequest_()
    : start(0)  {
    }
  LoadKnowledgeRequest_(const ContainerAllocator& _alloc)
    : start(0)  {
  (void)_alloc;
    }



   typedef int64_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadKnowledgeRequest_

typedef ::world_percept_assig3::LoadKnowledgeRequest_<std::allocator<void> > LoadKnowledgeRequest;

typedef boost::shared_ptr< ::world_percept_assig3::LoadKnowledgeRequest > LoadKnowledgeRequestPtr;
typedef boost::shared_ptr< ::world_percept_assig3::LoadKnowledgeRequest const> LoadKnowledgeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator1> & lhs, const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator1> & lhs, const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace world_percept_assig3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3cefc2a81c697b38bf59faba5b0cd16";
  }

  static const char* value(const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3cefc2a81c697b3ULL;
  static const uint64_t static_value2 = 0x8bf59faba5b0cd16ULL;
};

template<class ContainerAllocator>
struct DataType< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_percept_assig3/LoadKnowledgeRequest";
  }

  static const char* value(const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request is an integer called “start”\n"
"int64 start\n"
;
  }

  static const char* value(const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadKnowledgeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_percept_assig3::LoadKnowledgeRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<int64_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_LOADKNOWLEDGEREQUEST_H
