// Generated by gencpp from file world_percept_assig3/ProcessObject.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_PROCESSOBJECT_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_PROCESSOBJECT_H

#include <ros/service_traits.h>


#include <world_percept_assig3/ProcessObjectRequest.h>
#include <world_percept_assig3/ProcessObjectResponse.h>


namespace world_percept_assig3
{

struct ProcessObject
{

typedef ProcessObjectRequest Request;
typedef ProcessObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessObject
} // namespace world_percept_assig3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_percept_assig3::ProcessObject > {
  static const char* value()
  {
    return "32681a2870f0325b7d011635fd43aac7";
  }

  static const char* value(const ::world_percept_assig3::ProcessObject&) { return value(); }
};

template<>
struct DataType< ::world_percept_assig3::ProcessObject > {
  static const char* value()
  {
    return "world_percept_assig3/ProcessObject";
  }

  static const char* value(const ::world_percept_assig3::ProcessObject&) { return value(); }
};


// service_traits::MD5Sum< ::world_percept_assig3::ProcessObjectRequest> should match
// service_traits::MD5Sum< ::world_percept_assig3::ProcessObject >
template<>
struct MD5Sum< ::world_percept_assig3::ProcessObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::ProcessObject >::value();
  }
  static const char* value(const ::world_percept_assig3::ProcessObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::ProcessObjectRequest> should match
// service_traits::DataType< ::world_percept_assig3::ProcessObject >
template<>
struct DataType< ::world_percept_assig3::ProcessObjectRequest>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::ProcessObject >::value();
  }
  static const char* value(const ::world_percept_assig3::ProcessObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_percept_assig3::ProcessObjectResponse> should match
// service_traits::MD5Sum< ::world_percept_assig3::ProcessObject >
template<>
struct MD5Sum< ::world_percept_assig3::ProcessObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::ProcessObject >::value();
  }
  static const char* value(const ::world_percept_assig3::ProcessObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::ProcessObjectResponse> should match
// service_traits::DataType< ::world_percept_assig3::ProcessObject >
template<>
struct DataType< ::world_percept_assig3::ProcessObjectResponse>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::ProcessObject >::value();
  }
  static const char* value(const ::world_percept_assig3::ProcessObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_PROCESSOBJECT_H
