// Generated by gencpp from file world_percept_assig3/SendGoalResponse.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_SENDGOALRESPONSE_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_SENDGOALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace world_percept_assig3
{
template <class ContainerAllocator>
struct SendGoalResponse_
{
  typedef SendGoalResponse_<ContainerAllocator> Type;

  SendGoalResponse_()
    : success(false)  {
    }
  SendGoalResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SendGoalResponse_

typedef ::world_percept_assig3::SendGoalResponse_<std::allocator<void> > SendGoalResponse;

typedef boost::shared_ptr< ::world_percept_assig3::SendGoalResponse > SendGoalResponsePtr;
typedef boost::shared_ptr< ::world_percept_assig3::SendGoalResponse const> SendGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator1> & lhs, const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator1> & lhs, const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace world_percept_assig3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_percept_assig3/SendGoalResponse";
  }

  static const char* value(const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_percept_assig3::SendGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_percept_assig3::SendGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_SENDGOALRESPONSE_H
