// Generated by gencpp from file world_percept_assig3/SendGoal.msg
// DO NOT EDIT!


#ifndef WORLD_PERCEPT_ASSIG3_MESSAGE_SENDGOAL_H
#define WORLD_PERCEPT_ASSIG3_MESSAGE_SENDGOAL_H

#include <ros/service_traits.h>


#include <world_percept_assig3/SendGoalRequest.h>
#include <world_percept_assig3/SendGoalResponse.h>


namespace world_percept_assig3
{

struct SendGoal
{

typedef SendGoalRequest Request;
typedef SendGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendGoal
} // namespace world_percept_assig3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_percept_assig3::SendGoal > {
  static const char* value()
  {
    return "c6c193b83d729c060fe663d1f1fec285";
  }

  static const char* value(const ::world_percept_assig3::SendGoal&) { return value(); }
};

template<>
struct DataType< ::world_percept_assig3::SendGoal > {
  static const char* value()
  {
    return "world_percept_assig3/SendGoal";
  }

  static const char* value(const ::world_percept_assig3::SendGoal&) { return value(); }
};


// service_traits::MD5Sum< ::world_percept_assig3::SendGoalRequest> should match
// service_traits::MD5Sum< ::world_percept_assig3::SendGoal >
template<>
struct MD5Sum< ::world_percept_assig3::SendGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::SendGoal >::value();
  }
  static const char* value(const ::world_percept_assig3::SendGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::SendGoalRequest> should match
// service_traits::DataType< ::world_percept_assig3::SendGoal >
template<>
struct DataType< ::world_percept_assig3::SendGoalRequest>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::SendGoal >::value();
  }
  static const char* value(const ::world_percept_assig3::SendGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_percept_assig3::SendGoalResponse> should match
// service_traits::MD5Sum< ::world_percept_assig3::SendGoal >
template<>
struct MD5Sum< ::world_percept_assig3::SendGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_percept_assig3::SendGoal >::value();
  }
  static const char* value(const ::world_percept_assig3::SendGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_percept_assig3::SendGoalResponse> should match
// service_traits::DataType< ::world_percept_assig3::SendGoal >
template<>
struct DataType< ::world_percept_assig3::SendGoalResponse>
{
  static const char* value()
  {
    return DataType< ::world_percept_assig3::SendGoal >::value();
  }
  static const char* value(const ::world_percept_assig3::SendGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_PERCEPT_ASSIG3_MESSAGE_SENDGOAL_H
