(cl:defpackage rearrange-msg
  (:use )
  (:export
   "<NAVIGATEDRINKACTION>"
   "NAVIGATEDRINKACTION"
   "<NAVIGATEDRINKACTIONFEEDBACK>"
   "NAVIGATEDRINKACTIONFEEDBACK"
   "<NAVIGATEDRINKACTIONGOAL>"
   "NAVIGATEDRINKACTIONGOAL"
   "<NAVIGATEDRINKACTIONRESULT>"
   "NAVIGATEDRINKACTIONRESULT"
   "<NAVIGATEDRINKFEEDBACK>"
   "NAVIGATEDRINKFEEDBACK"
   "<NAVIGATEDRINKGOAL>"
   "NAVIGATEDRINKGOAL"
   "<NAVIGATEDRINKRESULT>"
   "NAVIGATEDRINKRESULT"
  ))

