; Auto-generated. Do not edit!


(cl:in-package rearrange-msg)


;//! \htmlinclude NavigateDrinkFeedback.msg.html

(cl:defclass <NavigateDrinkFeedback> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass NavigateDrinkFeedback (<NavigateDrinkFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateDrinkFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateDrinkFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rearrange-msg:<NavigateDrinkFeedback> is deprecated: use rearrange-msg:NavigateDrinkFeedback instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <NavigateDrinkFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rearrange-msg:success-val is deprecated.  Use rearrange-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateDrinkFeedback>) ostream)
  "Serializes a message object of type '<NavigateDrinkFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateDrinkFeedback>) istream)
  "Deserializes a message object of type '<NavigateDrinkFeedback>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateDrinkFeedback>)))
  "Returns string type for a message object of type '<NavigateDrinkFeedback>"
  "rearrange/NavigateDrinkFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateDrinkFeedback)))
  "Returns string type for a message object of type 'NavigateDrinkFeedback"
  "rearrange/NavigateDrinkFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateDrinkFeedback>)))
  "Returns md5sum for a message object of type '<NavigateDrinkFeedback>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateDrinkFeedback)))
  "Returns md5sum for a message object of type 'NavigateDrinkFeedback"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateDrinkFeedback>)))
  "Returns full string definition for message of type '<NavigateDrinkFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateDrinkFeedback)))
  "Returns full string definition for message of type 'NavigateDrinkFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateDrinkFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateDrinkFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateDrinkFeedback
    (cl:cons ':success (success msg))
))
