// Auto-generated. Do not edit!

// (in-package rearrange.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class NavigateDrinkResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_x = null;
      this.current_y = null;
      this.current_orientation_z = null;
      this.current_orientation_w = null;
    }
    else {
      if (initObj.hasOwnProperty('current_x')) {
        this.current_x = initObj.current_x
      }
      else {
        this.current_x = 0.0;
      }
      if (initObj.hasOwnProperty('current_y')) {
        this.current_y = initObj.current_y
      }
      else {
        this.current_y = 0.0;
      }
      if (initObj.hasOwnProperty('current_orientation_z')) {
        this.current_orientation_z = initObj.current_orientation_z
      }
      else {
        this.current_orientation_z = 0.0;
      }
      if (initObj.hasOwnProperty('current_orientation_w')) {
        this.current_orientation_w = initObj.current_orientation_w
      }
      else {
        this.current_orientation_w = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavigateDrinkResult
    // Serialize message field [current_x]
    bufferOffset = _serializer.float32(obj.current_x, buffer, bufferOffset);
    // Serialize message field [current_y]
    bufferOffset = _serializer.float32(obj.current_y, buffer, bufferOffset);
    // Serialize message field [current_orientation_z]
    bufferOffset = _serializer.float32(obj.current_orientation_z, buffer, bufferOffset);
    // Serialize message field [current_orientation_w]
    bufferOffset = _serializer.float32(obj.current_orientation_w, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavigateDrinkResult
    let len;
    let data = new NavigateDrinkResult(null);
    // Deserialize message field [current_x]
    data.current_x = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [current_y]
    data.current_y = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [current_orientation_z]
    data.current_orientation_z = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [current_orientation_w]
    data.current_orientation_w = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rearrange/NavigateDrinkResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5332c945bfb39768317dc31e78fb16d0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    float32 current_x
    float32 current_y
    float32 current_orientation_z
    float32 current_orientation_w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavigateDrinkResult(null);
    if (msg.current_x !== undefined) {
      resolved.current_x = msg.current_x;
    }
    else {
      resolved.current_x = 0.0
    }

    if (msg.current_y !== undefined) {
      resolved.current_y = msg.current_y;
    }
    else {
      resolved.current_y = 0.0
    }

    if (msg.current_orientation_z !== undefined) {
      resolved.current_orientation_z = msg.current_orientation_z;
    }
    else {
      resolved.current_orientation_z = 0.0
    }

    if (msg.current_orientation_w !== undefined) {
      resolved.current_orientation_w = msg.current_orientation_w;
    }
    else {
      resolved.current_orientation_w = 0.0
    }

    return resolved;
    }
};

module.exports = NavigateDrinkResult;
