(cl:defpackage rearrange-srv
  (:use )
  (:export
   "GETSCENEOBJECTLIST"
   "<GETSCENEOBJECTLIST-REQUEST>"
   "GETSCENEOBJECTLIST-REQUEST"
   "<GETSCENEOBJECTLIST-RESPONSE>"
   "GETSCENEOBJECTLIST-RESPONSE"
   "SETINITTIAGOPOSE"
   "<SETINITTIAGOPOSE-REQUEST>"
   "SETINITTIAGOPOSE-REQUEST"
   "<SETINITTIAGOPOSE-RESPONSE>"
   "SETINITTIAGOPOSE-RESPONSE"
   "UPDATEOBJECTLIST"
   "<UPDATEOBJECTLIST-REQUEST>"
   "UPDATEOBJECTLIST-REQUEST"
   "<UPDATEOBJECTLIST-RESPONSE>"
   "UPDATEOBJECTLIST-RESPONSE"
  ))

